version: '3.1'

services:
  scraptt-db:
    image: cockroachdb/cockroach:v2.0.4 
    ports:
      - 54321:26257
      - 18080:8080
    command: >
      shell -c '
      echo "Asia/Taipei" > /etc/timezone
      && rm /etc/localtime
      && dpkg-reconfigure -f noninteractive tzdata
      && /cockroach/cockroach start --insecure'
    volumes:
      - scraptt-db:/cockroach/cockroach-data
    networks:
      - scraptt-network

  scraptt-db-N:
    image: cockroachdb/cockroach:v2.0.4
    command: >
      shell -c '
      echo "Asia/Taipei" > /etc/timezone
      && rm /etc/localtime
      && dpkg-reconfigure -f noninteractive tzdata
      && /cockroach/cockroach start --insecure --join=scraptt-db'
    depends_on:
      - scraptt-db
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    networks:
      - scraptt-network

  scraptt:
    image: scraptt
    volumes:
      - scraptt:/var/log
    command: >
      sh -c '
      for i in `seq 1 15`; do wget --spider -q scrapyd:6800 && break; sleep 1; done
      && scrapyd-deploy scraptt -p scraptt
      && python -c "from scraptt.postgres.db import init_db; init_db()"
      && tail -f /dev/null
      '
    depends_on:
      - scraptt-db
      - scrapyd
    networks:
      - scraptt-network

  scrapyd:
    image: amigcamel/alpine-scrapy-psycopg2:latest # TODO: -- can be even smaller
    volumes:
      - ./scrapyd.cfg:/etc/scrapyd/scrapyd.conf
      - ./requirements.txt:/tmp/requirements1.txt
      - ./scraptt-pipeline/requirements.txt:/tmp/requirements2.txt
    ports:
      - 16800:6800
    environment:
      - "TZ=Asia/Taipei"
    command: >
      sh -c '
      apk add --update tzdata
      && pip install scrapyd
      && pip install -r /tmp/requirements1.txt -r /tmp/requirements2.txt
      && scrapyd
      '
    networks:
      - scraptt-network

volumes:
  scraptt:
  scraptt-db:

networks:
  scraptt-network:
