version: '3.1'

services:
  scraptt-db:
    image: cockroachdb/cockroach:v2.0.4 
    ports:
      - 54321:26257
      - 18080:8080
    volumes:
      - ./mount/data:/cockroach/cockroach-data
    command: start --insecure
    networks:
      - scraptt-network

  scraptt:
    build: .
    volumes:
      - ./mount/crawler/:/usr/local/var
    tty: true
    depends_on:
      - scraptt-db
    networks:
      - scraptt-network

networks:
  scraptt-network:

