version: '3.1'

services:
  scraptt-db:
    image: cockroachdb/cockroach:v2.0.4 
    ports:
      - 54321:26257
      - 18080:8080
    volumes:
      - ./mount/data:/cockroach/cockroach-data
    command: start --insecure
    networks:
      - scraptt-network

  scraptt:
    build: .
    volumes:
      - ./mount/crawler/:/usr/local/var
    command: sh -c 'scrapyd-deploy scraptt -p scraptt && tail -f /dev/null'
    depends_on:
      - scraptt-db
      - scrapyd
    networks:
      - scraptt-network

  scrapyd:
    image: amigcamel/alpine-scrapy-psycopg2:latest # TODO: -- can be even smaller
    volumes:
      - ./scrapyd.cfg:/etc/scrapyd/scrapyd.conf
    ports:
      - 16800:6800
    command: sh -c 'pip install scrapyd && scrapyd'
    networks:
      - scraptt-network

networks:
  scraptt-network:

