version: '3.1'

services:
  scraptt-db:
    image: cockroachdb/cockroach:v2.0.4 
    ports:
      - 54321:26257
      - 18080:8080
    volumes:
      - ./mount/data:/cockroach/cockroach-data
    command: >
      shell -c '
      echo "Asia/Taipei" > /etc/timezone
      && rm /etc/localtime
      && dpkg-reconfigure -f noninteractive tzdata
      && /cockroach/cockroach start --insecure'
    networks:
      - scraptt-network

  scraptt:
    build: .
    volumes:
      - ./mount/scraptt/log:/var/log
    command: >
      sh -c '
      for i in `seq 1 15`; do wget --spider -q scrapyd:6800 && break; sleep 1; done
      && scrapyd-deploy scraptt -p scraptt
      && tail -f /dev/null
      '
    depends_on:
      - scraptt-db
      - scrapyd
    networks:
      - scraptt-network

  scrapyd:
    image: amigcamel/alpine-scrapy-psycopg2:latest # TODO: -- can be even smaller
    volumes:
      - ./scrapyd.cfg:/etc/scrapyd/scrapyd.conf
    ports:
      - 16800:6800
    environment:
      - "TZ=Asia/Taipei"
    command: >
      sh -c '
      apk add --update tzdata
      && pip install scrapyd
      && pip install python-dateutil pyquery
      && scrapyd
      '
    networks:
      - scraptt-network

networks:
  scraptt-network:

